### ISSUE TITLE
Find replacement for "Default sender" - before 4.7 this was the "Creator" of a "Mail" topic

### ISSUE THREAD

**Issue by mukil** [mukil/dm4-mail#2]
As of DeepaMehta 4.7 "acService.getCreator()" is no longer.
The proper "fallback" solution would be to user the first "Signature" for the authenticated user.

**Comment by jri** [comment]
In 4.7 (and later) the Access Control Service still has `getCreator()`.
Possibly you mixed it up with `getOwner()`.
